spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DATASOURCE_DB}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: customer-service
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ecommerce
            user-name-attribute: preferred_username
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ecommerce
    password: ecommerce

keycloak:
  auth-server-url: http://keycloak:8080
  realm: ecommerce
  client-id: customer-service
  client-secret: ${CLIENT_SECRET}

server:
  port: 8081
